### ISSUE TITLE
Creation of a collection when importing a single item

### ISSUE THREAD

**Issue by Leblance** [utlib/IiifItems#11]
Hello,

We have installed the IIIF Toolkit on Omeka (version 2.4). We succed to import items (books) from IIIF servers. But when we do it, Omeka creates a new collection (which corresponds to the manifest, so to one book) and several items (which correspond to the canvases, so to the images of this book). It becomes then difficult to manage the collection, because we have to create "meta-collections". Is it possible when we import a book (via IIIF import) that its manifest becomes an item with multiple canvases, and not a collection ?

Thanks in advance !

**Comment by dicksonlaw583** [comment]
We currently don't have a plan for supporting that mapping scheme, since it would break the plugin's ability to interoperate with other item-based plugins. However, we have an upcoming update that would allow collections to nest, making it easier to manage books in a group.

**Comment by dicksonlaw583** [comment]
Collections have been able to nest since 1.1.0.
