### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by sarahloleet** [utlib/IiifItems#12]
Working through Reclaim hosting, I've tried to install the IIIF Plugin and have received this error message:

Omeka_Validate_Exception: Name: Name of element set must be unique. in /home/peripher/public_html/application/libraries/Omeka/Record/AbstractRecord.php:535
Stack trace:
#0 /home/peripher/public_html/application/libraries/Omeka/Record/Builder/AbstractBuilder.php(67): Omeka_Record_AbstractRecord->save()
#1 /home/peripher/public_html/application/libraries/globals.php(740): Omeka_Record_Builder_AbstractBuilder->build()
#2 /home/peripher/public_html/plugins/IiifItems/libraries/IiifItems/Integration/Files.php(24): insert_element_set(Array, Array)
#3 /home/peripher/public_html/plugins/IiifItems/IiifItemsPlugin.php(42): IiifItems_Integration_Files->install()
#4 /home/peripher/public_html/application/libraries/Omeka/Plugin/Broker.php(145): IiifItemsPlugin->hookInstall(Array)
#5 /home/peripher/public_html/application/libraries/Omeka/Plugin/Installer.php(130): Omeka_Plugin_Broker->callHook('install', Array, Object(Plugin))
#6 /home/peripher/public_html/application/controllers/PluginsController.php(97): Omeka_Plugin_Installer->install(Object(Plugin))
#7 /home/peripher/public_html/application/libraries/Zend/Controller/Action.php(516): PluginsController->installAction()
#8 /home/peripher/public_html/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('installAction')
#9 /home/peripher/public_html/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#10 /home/peripher/public_html/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#11 /home/peripher/public_html/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#12 /home/peripher/public_html/application/libraries/Omeka/Application.php(77): Zend_Application->run()
#13 /home/peripher/public_html/admin/index.php(28): Omeka_Application->run()
#14 {main}

Any advice on how to debug this error?  Thank you.

**Comment by dicksonlaw583** [comment]
This appears to be the result of an interrupted installation being refreshed. Please go to Settings > Element Sets and delete all IIIF-related element sets, then retry.

**Comment by sarahloleet** [comment]
I did retry and received the same error message.  Although the installation did not fully work, it recreated the three IIIF Metadata Sets (Item, File, and Collection) that I deleted.

**Comment by dicksonlaw583** [comment]
Where did you download the plugin from? If it came from omeka.org, please retry with a download of the current master branch ([link](https://github.com/utlib/IiifItems/archive/master.zip)). Remember to rename the extracted directory from `IiifItems-master` to `IiifItems`.

**Comment by sarahloleet** [comment]
I did download the ling from omeka.org.  I just tried uploading the current master branch, renaming the file as required, and received the following error message: "The server encountered an internal error or misconfiguration and was unable to complete your request."

**Comment by dicksonlaw583** [comment]
Please un-comment the `SetEnv APPLICATION_ENV development` line from your Omeka installation's `.htaccess` file and post the complete error trace.

As an added note, IIIF Toolkit requires a working job queue in order to set up. Please try out other plugins requiring background jobs (e.g. CSV Import) and see if you get the same errors there. If you do, please contact your host about how to locate your local PHP-CLI path.

**Comment by sarahloleet** [comment]
Thank you for your help.  I will speak with my host about my local PHP-CLI
path.
