### ISSUE TITLE
 Display image in Omeka

### ISSUE THREAD

**Issue by Leonardoeb** [utlib/IiifItems#13]
Hello Friend,

could they help me on how to display images on Omeka using the IIF plufin? I have already installed the IIF but I am not sure how to import images and display in Omeka. Do I need an image server?

**Comment by dicksonlaw583** [comment]
You would need an image server such as Loris if the images come from Omeka itself. Please see:

- The IIIF Prefix configuration: https://github.com/utlib/IiifItems/wiki/Configurations
- Example configuration for Loris: https://github.com/utlib/IiifItems/wiki/Reference-IIIF-Image-Server-Configuration-for-Loris

If the images come from your institution's IIIF image server and you have manifests for it, you can use the Import form (https://github.com/utlib/IiifItems/wiki/Importing-IIIF-Content). Please make sure that the image server is configured to allow access from your site.

**Comment by dicksonlaw583** [comment]
Resolved over email.
