### ISSUE TITLE
Omeka classic iiif toolkit - item type metadata (Omeka record exception error)

### ISSUE THREAD

**Issue by ghost** [utlib/IiifItems#15]
Hello everyone. 
Omeka record exception error ocuured, after installed the iiif toolkit on omeka classic 2.6.1.  when i clicked the item image in from the admin site after installed the iiif toolkit on omeka classic 2.6.1 the error comes.. Need help. The error details is below
 
![image 1](https://user-images.githubusercontent.com/45758834/50581211-9a10bd80-0e7d-11e9-9e21-f2a297a5604a.png)

**Comment by dicksonlaw583** [comment]
Please allow time for the setup task to run, which will assign an initial ID to all items. You can check on its progress in the admin interface's IIIF Toolkit > Status.

**Comment by ghost** [comment]
> Please allow time for the setup task to run, which will assign an initial ID to all items. You can check on its progress in the admin interface's IIIF Toolkit > Status.
Here is the screen shot of IIIF toolkit status. Adding the UUID for the all the 444 items and collections has been completed. 
![screenshot_2019-01-03 iiif toolkit my keystone omeka admin](https://user-images.githubusercontent.com/45758834/50623563-19b19180-0f3d-11e9-8fed-cbf364004967.png)

**Comment by dicksonlaw583** [comment]
That error should be gone once that "Adding UUID" job finishes running. If the error comes from the items that failed to import, please delete those as their metadata is likely incomplete.

**Comment by ghost** [comment]
> That error should be gone once that "Adding UUID" job finishes running. If the error comes from the items that failed to import, please delete those as their metadata is likely incomplete.

Thank you  (dicksonlaw583) i have restored my previous database backup,removed the you tube import and reinstalled the iiif toolkit. Now the error is gone.
