### ISSUE TITLE
Images in annotation text lose size tags

### ISSUE THREAD

**Issue by jaguillette** [utlib/IiifItems#18]
It looks like when you set the size of an image in the text of an annotation, the height and width are saved as part of the <img> tag, but it gets removed somewhere before it gets displayed on the front end. This is the way that the image option in the annotation editor sets up the image, but the size information gets lost in translation somewhere.

**Comment by jaguillette** [comment]
For reference, the image tag keeps its height and width on the details page for the annotation as an item: http://workingwomenoftheeast.omeka.fas.harvard.edu/items/show/1117

But does not keep that information on the page for the item that it annotates: http://workingwomenoftheeast.omeka.fas.harvard.edu/items/show/101

**Comment by dicksonlaw583** [comment]
Try locating this line in `views/shared/mirador/mirador.js` near the bottom:
```
'img': ['src', 'alt'],
```
And changing it to:
```
'img': ['src', 'alt', 'width', 'height'],
```
This should stop the viewer's HTML sanitizer from stripping away your image sizes.

**Comment by dicksonlaw583** [comment]
PR containing fix merged, closing.
