### ISSUE TITLE
Troubleshooting IIIF Hosting configuration

### ISSUE THREAD

**Issue by adehner** [utlib/IiifItems#19]
Working in Omeka Classic v.2.7.1
IIIF v.1.1
IIIF Toolkit v.1.1.0
Using a free IIIF Hosting account for testing purposes

The mirador viewer isn't displaying in my items, and I'm getting an error that zoom is undefined. Every import fails. Something(s) in my configuration are incorrect. I'm wondering about the following, for starters...

- In Omeka > IIIF Toolkit > Import: I'm not sure whether to enter a IIIF Hosting url or an Omeka url
- In Omeka's public item page: instead of a mirador viewer, I'm seeing my item's file. Clicking on the file does nothing. In the IIIF Manifest block, I see a black box with the prompt 'addItem'.

Thanks in advance for your assistance.

**Comment by dicksonlaw583** [comment]
- If all import jobs fail, consider checking your job queue's setup with [this plugin](https://github.com/utlib/JobDiagnostics) first.
- The URL field in Omeka > IIIF Toolkit > Import takes a URL leading to a IIIF 2.x manifest. Here is an example: https://digital.library.villanova.edu/Item/vudl:94056/Manifest
- Mirador viewers don't work for your own content until Plugins > IIIF Toolkit > Configure > IIIF Prefix is configured. Please consult your IIIF image server provider's documentation for how to set up a HTTP resolver and what the resulting IIIF image API URL looks like. Also make sure that the IIIF image server is using the 2.x Image API standard, not 3.x.
- If your site is hosted on HTTPS, make sure the IIIF server also serves on HTTPS.

**Comment by adehner** [comment]
Thank you. Importing with the Villanova manifest works and the Villanova images display in the Mirador viewer. Great to see how this is supposed to work!

So I believe my issues relate to my server. Thanks so much.
