### ISSUE TITLE
'Omeka_Validate_Exception' Error Message?

### ISSUE THREAD

**Issue by AFRivers** [utlib/IiifItems#2]
Hi there! 

I'm trying to use this toolkit for a digital gallery project on my website, but even though I followed the first couple of instructions (i.e. cloning the repository to the `plugins` directory of my Omeka repository) I keep getting the same error message whenever I try to install the plugin: 

> exception 'Omeka_Validate_Exception' with message 'Name: Name of element set must be unique.' in /home/delosrio/public_html/gallery_2/application/libraries/Omeka/Record/AbstractRecord.php:535
Stack trace:
#0 /home/delosrio/public_html/gallery_2/application/libraries/Omeka/Record/Builder/AbstractBuilder.php(67): Omeka_Record_AbstractRecord->save()
#1 /home/delosrio/public_html/gallery_2/application/libraries/globals.php(740): Omeka_Record_Builder_AbstractBuilder->build()
#2 /home/delosrio/public_html/gallery_2/plugins/IiifItems/libraries/IiifItems/Integration/Files.php(26): insert_element_set(Array, Array)
#3 /home/delosrio/public_html/gallery_2/plugins/IiifItems/IiifItemsPlugin.php(42): IiifItems_Integration_Files->install()
#4 [internal function]: IiifItemsPlugin->hookInstall(Array)
#5 /home/delosrio/public_html/gallery_2/application/libraries/Omeka/Plugin/Broker.php(145): call_user_func(Array, Array)
#6 /home/delosrio/public_html/gallery_2/application/libraries/Omeka/Plugin/Installer.php(130): Omeka_Plugin_Broker->callHook('install', Array, Object(Plugin))
#7 /home/delosrio/public_html/gallery_2/application/controllers/PluginsController.php(97): Omeka_Plugin_Installer->install(Object(Plugin))
#8 /home/delosrio/public_html/gallery_2/application/libraries/Zend/Controller/Action.php(516): PluginsController->installAction()
#9 /home/delosrio/public_html/gallery_2/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('installAction')
#10 /home/delosrio/public_html/gallery_2/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /home/delosrio/public_html/gallery_2/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#12 /home/delosrio/public_html/gallery_2/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#13 /home/delosrio/public_html/gallery_2/application/libraries/Omeka/Application.php(77): Zend_Application->run()
#14 /home/delosrio/public_html/gallery_2/admin/index.php(28): Omeka_Application->run()
#15 {main}

I am fairly new to this aspect of web design, so I was hoping someone could explain what's causing this error and if there is any way of fixing it. 

Thanks!

**Comment by dicksonlaw583** [comment]
Please provide the following information to help us replicate the error:

- The version number of Omeka, MySQL, PHP
- Name and version of any other plugins you are using
- A screenshot or listing of Element Sets on your Omeka (Settings > Element Sets).
- A screenshot or listing of the contents for the Element Set "IIIF File Metadata" (if it is found).

**Comment by AFRivers** [comment]
- I’m running Omeka 2.5, MySQL 5..5.54, and PHP 5.6.30
- I have COinS 2.03, Exhibit Builder 3.3.3, and Simple Pages 3.08, but none of them are installed.
- And the two required screenshots should be attached below: [cid:00435A1F-44AE-49E0-8240-B3C71F43559B] [cid:328A423F-2555-4762-A319-078C5F5ABCC0]

Thanks again for the help!

On Jul 6, 2017, at 4:43 PM, Dickson Law <notifications@github.com<mailto:notifications@github.com>> wrote:


Please provide the following information to help us replicate the error:

  *   The version number of Omeka, MySQL, PHP
  *   Name and version of any other plugins you are using
  *   A screenshot or listing of Element Sets on your Omeka (Settings > Element Sets).
  *   A screenshot or listing of the contents for the Element Set "IIIF File Metadata" (if it is found).

**Comment by dicksonlaw583** [comment]
The screenshots appear to have been filtered out of your response. Please contact me directly at dickson.law@utoronto.ca.

**Comment by dicksonlaw583** [comment]
@AFRivers Please try the ```fix-install-crash``` branch and let me know whether it installs properly.

Link: https://github.com/utlib/IiifItems/tree/fix-install-crash

**Comment by AFRivers** [comment]
I tried to go through the installation process with the new branch, but now I am getting this new error: 

> exception 'Omeka_Validate_Exception' with message 'Name: An element named "UUID" already exists for the "IIIF Collection Metadata" element set.' in /home/delosrio/public_html/gallery_2/application/libraries/Omeka/Record/AbstractRecord.php:535
Stack trace:
#0 /home/delosrio/public_html/gallery_2/application/models/ElementSet.php(99): Omeka_Record_AbstractRecord->save()
#1 [internal function]: ElementSet->afterSave(Array)
#2 /home/delosrio/public_html/gallery_2/application/libraries/Omeka/Record/AbstractRecord.php(277): call_user_func(Array, Array)
#3 /home/delosrio/public_html/gallery_2/application/libraries/Omeka/Record/AbstractRecord.php(550): Omeka_Record_AbstractRecord->runCallbacks('afterSave', Array)
#4 /home/delosrio/public_html/gallery_2/plugins/IiifItems/libraries/IiifItems/Migration/0_0_1_6.php(18): Omeka_Record_AbstractRecord->save()
#5 /home/delosrio/public_html/gallery_2/plugins/IiifItems/libraries/IiifItems/Integration/System.php(75): IiifItems_Migration_0_0_1_6->up()
#6 /home/delosrio/public_html/gallery_2/plugins/IiifItems/libraries/IiifItems/Integration/System.php(21): IiifItems_Integration_System->__addUuids()
#7 /home/delosrio/public_html/gallery_2/plugins/IiifItems/IiifItemsPlugin.php(42): IiifItems_Integration_System->install()
#8 [internal function]: IiifItemsPlugin->hookInstall(Array)
#9 /home/delosrio/public_html/gallery_2/application/libraries/Omeka/Plugin/Broker.php(145): call_user_func(Array, Array)
#10 /home/delosrio/public_html/gallery_2/application/libraries/Omeka/Plugin/Installer.php(130): Omeka_Plugin_Broker->callHook('install', Array, Object(Plugin))
#11 /home/delosrio/public_html/gallery_2/application/controllers/PluginsController.php(97): Omeka_Plugin_Installer->install(Object(Plugin))
#12 /home/delosrio/public_html/gallery_2/application/libraries/Zend/Controller/Action.php(516): PluginsController->installAction()
#13 /home/delosrio/public_html/gallery_2/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('installAction')
#14 /home/delosrio/public_html/gallery_2/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#15 /home/delosrio/public_html/gallery_2/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#16 /home/delosrio/public_html/gallery_2/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#17 /home/delosrio/public_html/gallery_2/application/libraries/Omeka/Application.php(77): Zend_Application->run()
#18 /home/delosrio/public_html/gallery_2/admin/index.php(28): Omeka_Application->run()
#19 {main}

**Comment by dicksonlaw583** [comment]
@AFRivers I have just added a catch for that error in your reply. Could you try again?

**Comment by AFRivers** [comment]
@dicksonlaw583 Unfortunately, I tried again with the catch and this time it produced the following new error: 

> exception 'RuntimeException' with message 'The configured PHP path (/usr/bin/php) does not point to a PHP-CLI binary.' in /home/delosrio/public_html/gallery_2/application/libraries/Omeka/Job/Process/Dispatcher.php:124
> Stack trace:
> #0 /home/delosrio/public_html/gallery_2/application/libraries/Omeka/Job/Process/Dispatcher.php(93): Omeka_Job_Process_Dispatcher::_checkCliPath('/usr/bin/php')
> #1 /home/delosrio/public_html/gallery_2/application/libraries/Omeka/Job/Process/Dispatcher.php(28): Omeka_Job_Process_Dispatcher::getPHPCliPath()
> #2 /home/delosrio/public_html/gallery_2/application/libraries/Omeka/Job/Dispatcher/Adapter/BackgroundProcess.php(31): Omeka_Job_Process_Dispatcher::startProcess('Omeka_Job_Proce...', Object(User), Array)
> #3 /home/delosrio/public_html/gallery_2/application/libraries/Omeka/Job/Dispatcher/Default.php(150): Omeka_Job_Dispatcher_Adapter_BackgroundProcess->send('{"className":"I...', Array)
> #4 /home/delosrio/public_html/gallery_2/plugins/IiifItems/libraries/IiifItems/Migration/0_0_1_6.php(38): Omeka_Job_Dispatcher_Default->sendLongRunning('IiifItems_Job_A...', Array)
> #5 /home/delosrio/public_html/gallery_2/plugins/IiifItems/libraries/IiifItems/Integration/System.php(75): IiifItems_Migration_0_0_1_6->up()
> #6 /home/delosrio/public_html/gallery_2/plugins/IiifItems/libraries/IiifItems/Integration/System.php(21): IiifItems_Integration_System->__addUuids()
> #7 /home/delosrio/public_html/gallery_2/plugins/IiifItems/IiifItemsPlugin.php(42): IiifItems_Integration_System->install()
> #8 [internal function]: IiifItemsPlugin->hookInstall(Array)
> #9 /home/delosrio/public_html/gallery_2/application/libraries/Omeka/Plugin/Broker.php(145): call_user_func(Array, Array)
> #10 /home/delosrio/public_html/gallery_2/application/libraries/Omeka/Plugin/Installer.php(130): Omeka_Plugin_Broker->callHook('install', Array, Object(Plugin))
> #11 /home/delosrio/public_html/gallery_2/application/controllers/PluginsController.php(97): Omeka_Plugin_Installer->install(Object(Plugin))
> #12 /home/delosrio/public_html/gallery_2/application/libraries/Zend/Controller/Action.php(516): PluginsController->installAction()
> #13 /home/delosrio/public_html/gallery_2/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('installAction')
> #14 /home/delosrio/public_html/gallery_2/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
> #15 /home/delosrio/public_html/gallery_2/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
> #16 /home/delosrio/public_html/gallery_2/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
> #17 /home/delosrio/public_html/gallery_2/application/libraries/Omeka/Application.php(77): Zend_Application->run()
> #18 /home/delosrio/public_html/gallery_2/admin/index.php(28): Omeka_Application->run()
> #19 {main}

**Comment by dicksonlaw583** [comment]
Please update the ```background.php.path``` key in your Omeka installation's ```application/config/config.ini``` file to match the actual path to your PHP binary. If you are on a shared host or institutional server, you should consult an administrator for advice. All background-running jobs, including the plugin's installation routine and IIIF manifest importer, rely on this setting.

Here is a similar discussion from the old Omeka forums for another plugin, running on BlueHost: http://omeka.org/forums-legacy/topic/csv-import-plugin-not-working-on-shared-host

**Comment by AFRivers** [comment]
That did it! The plugin is finally installed. Thank you for all your help!

**Comment by dicksonlaw583** [comment]
You are welcome. I hope you will enjoy using the plugin.

Resolved via PR #3.
