### ISSUE TITLE
Images don't load in Mirador viewer

### ISSUE THREAD

**Issue by DigExpCon** [utlib/IiifItems#23]
No images appear in the Mirador viewer. It's trying to load images from: https://[website]/files/original/0404582062ebcbf52b5d59d17090538b.jpg/full/122,/0/default.jpg

We're not using an image server, so maybe it's looking for tiles that don't exist? 

As an example, see: https://test.cdoclibraries.org/items/show/18

**Comment by ShawnWon** [comment]
Hi, DigExpCon, I'm very new to omeka and IIIf. I had my IIIF source displayed in Mirador viewer, then compared the HTML code with yours. It looks Mirador viewer on your example page didn't get the correct source URL.

![image](https://user-images.githubusercontent.com/47803938/103458377-45d99600-4d42-11eb-9384-37f501c8238e.png)

Below screenshot is from mine which is displaying:

![image](https://user-images.githubusercontent.com/47803938/103458416-cf896380-4d42-11eb-9357-cbb735c5adb7.png)

Not sure how come it didn't get the correct URL,  one possibility that came into my mind is the "IIIF prefix" in the configuration of IIIFToolkit. Did you set the IIIF prefix?

![image](https://user-images.githubusercontent.com/47803938/103458476-9dc4cc80-4d43-11eb-8cf1-bc95f8ac3592.png)

**Comment by DigExpCon** [comment]
Thank you for that information--and sorry for the late reply. We don't have a IIIF image server, but I had naively hoped we could use the plugin without one. Without an image server the plugin does generate a IIIF manifest with correct urls for the original images, but the viewer doesn't work and urls in the manifest for anno.json or sequence.json point to things that don't actually exist. So I guess I will chalk this up to my own lack of understanding what the plugin could do without an image server.
