### ISSUE TITLE
Manifests generate with height and width set to 0 when using S3 storage adapter

### ISSUE THREAD

**Issue by jaguillette** [utlib/IiifItems#24]
We use the S3 storage adapter in our installation of Omeka, and found that when using less permissive versions of Mirador, manifests were not accepted by the viewer because they lacked an image height and width. Looking at the code, it seems that when there isn't an existing canvas JSON, the height and width are determined with a php `getimagesize` call that assumes the images are stored locally. Since ours aren't the call fails, and the height and width remain at their initial value of zero. It seems possible to fix by generating the height and width from the image metadata already stored in Omeka instead.

**Comment by dicksonlaw583** [comment]
Fixed: https://github.com/utlib/IiifItems/commit/ee004e9ea60288fe9556ab609bf958f80de112ae
