### ISSUE TITLE
Error upon installing the latest plugin on Classic

### ISSUE THREAD

**Issue by GitByrd** [utlib/IiifItems#27]
Can someone help me understand this? I installed the latest version available on Omeka Classic and it gives me this error right after I click the install button in Classic: 

"RuntimeException
The configured PHP path (/bin/php) does not point to a PHP-CLI binary"

Thanks

**Comment by dicksonlaw583** [comment]
This is an issue with your Omeka installation's job runner, not this plugin in particular. See:

- [Setting the PHP Path](https://omeka.org/classic/docs/Technical/Setting_PHP_Path/)
- [CSV Importer and PHP CLI path](https://forum.omeka.org/t/csv-importer-and-php-cli-path/11388)

**Comment by dicksonlaw583** [comment]
Closed for inactivity. Please open a new ticket if the problem persists.
