### ISSUE TITLE
Form field missing label on search form

### ISSUE THREAD

**Issue by DigExpCon** [utlib/IiifItems#33]
In the file iiifItems/libraries/IiifItems/Integration/Collections.php, line 330: the FOR attribute for the input label is "include_submembers", but the input's id is "submembers." The label FOR and input ID should match.

**Comment by dicksonlaw583** [comment]
Thank you for reporting this. I have added in a fix: fb7f13a3fba6f96ab436c2bf464b6a12d3caa59c
