### ISSUE TITLE
"This is not a valid plugin" IIIF Toolkit Omeka Plugin

### ISSUE THREAD

**Issue by trishaoconnor** [utlib/IiifItems#9]
[IIIF-Toolkit-with-Mirador-1.0.0.zip](https://github.com/utlib/IiifItems/files/1257238/IIIF-Toolkit-with-Mirador-1.0.0.zip)
Tried to upload this plugin to Omeka by unzipping on my desktop and then manually uploading in my FTP client under plugins. It's listed under plugins but not recognised as a valid plugin so I can't install it. 

Any help would be greatly appreciated. 
![image](https://user-images.githubusercontent.com/10034768/29835697-b256cd14-8cea-11e7-8dd8-817ecc6a7c99.png)

**Comment by pfabri** [comment]
You have to rename the plugin folder to `IiifItems`. The error message then goes away and the 'Install' button appears.

Rather unfortunately, though, at least for me, clicking on 'Install' then results in this:

![image](https://user-images.githubusercontent.com/16960025/30037244-5172cc18-91b9-11e7-91ea-548190c79bdb.png)

**Error.log**
```
2017-09-04T19:40:00+00:00 ERR (3): RuntimeException: The configured PHP path () does not point to a PHP-CLI binary. in /home/fabrizoltan/public_html/application/libraries/Omeka/Job/Process/Dispatcher.php:124
Stack trace:
#0 /home/fabrizoltan/public_html/application/libraries/Omeka/Job/Process/Dispatcher.php(93): Omeka_Job_Process_Dispatcher::_checkCliPath(NULL)
#1 /home/fabrizoltan/public_html/application/libraries/Omeka/Job/Process/Dispatcher.php(28): Omeka_Job_Process_Dispatcher::getPHPCliPath()
#2 /home/fabrizoltan/public_html/application/libraries/Omeka/Job/Dispatcher/Adapter/BackgroundProcess.php(31): Omeka_Job_Process_Dispatcher::startProcess('Omeka_Job_Proce...', Object(User), Array)
#3 /home/fabrizoltan/public_html/application/libraries/Omeka/Job/Dispatcher/Default.php(150): Omeka_Job_Dispatcher_Adapter_BackgroundProcess->send('{"className":"I...', Array)
#4 /home/fabrizoltan/public_html/plugins/IiifItems/libraries/IiifItems/Migration/0_0_1_6.php(38): Omeka_Job_Dispatcher_Default->sendLongRunning('IiifItems_Job_A...', Array)
#5 /home/fabrizoltan/public_html/plugins/IiifItems/libraries/IiifItems/Integration/System.php(75): IiifItems_Migration_0_0_1_6->up()
#6 /home/fabrizoltan/public_html/plugins/IiifItems/libraries/IiifItems/Integration/System.php(21): IiifItems_Integration_System->__addUuids()
#7 /home/fabrizoltan/public_html/plugins/IiifItems/IiifItemsPlugin.php(42): IiifItems_Integration_System->install()
#8 /home/fabrizoltan/public_html/application/libraries/Omeka/Plugin/Broker.php(145): IiifItemsPlugin->hookInstall(Array)
#9 /home/fabrizoltan/public_html/application/libraries/Omeka/Plugin/Installer.php(130): Omeka_Plugin_Broker->callHook('install', Array, Object(Plugin))
#10 /home/fabrizoltan/public_html/application/controllers/PluginsController.php(97): Omeka_Plugin_Installer->install(Object(Plugin))
#11 /home/fabrizoltan/public_html/application/libraries/Zend/Controller/Action.php(516): PluginsController->installAction()
#12 /home/fabrizoltan/public_html/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('installAction')
#13 /home/fabrizoltan/public_html/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#14 /home/fabrizoltan/public_html/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#15 /home/fabrizoltan/public_html/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#16 /home/fabrizoltan/public_html/application/libraries/Omeka/Application.php(77): Zend_Application->run()
#17 /home/fabrizoltan/public_html/admin/index.php(28): Omeka_Application->run()
#18 {main}
```
But the database gets a partial update from the failed install, the 'element sets', for example are added.

**Comment by dicksonlaw583** [comment]
@trishaoconnor:

As @pfabri mentioned, the directory should be named ```IiifItems``` when uploaded to your host. Please also make sure that your host isn't blocking the file types used in the plugin (especially ```.ini```) and has a high enough file size limit to accommodate the files (the largest is the 3.1MB built-in Mirador JS file).

**Comment by pfabri** [comment]
Well, the above error suggest that the problem is that PHP-CLI can't be found. I've tried the usual `/usr/bin/php-cli` but to no avail.

**Comment by dicksonlaw583** [comment]
@pfabri:

The exact path varies with the server's setup, ```/usr/bin/php-cli``` is one of several common ones but it might not work for you. This is an issue on your Omeka instance's setup, not the plugin.

Some people got it working as-is, some with ```/usr/bin/php```, some with ```/usr/bin/php-cli```, and some with something else entirely on shared hosts (see [this old Omeka forum post](http://omeka.org/forums-legacy/topic/csv-import-plugin-error-message)).

**Comment by pfabri** [comment]
@dicksonlaw583:

Yes, that's clear. What is surprising, though, is that I do get a response if I type in `/usr/bin/php-cli -v` on my server, but still the plugin reports it's not there.

Any ideas?

**Comment by dicksonlaw583** [comment]
Try going into ```application/config/config.ini``` in your Omeka installation and changing its ```background.php.path``` entry to ```"/usr/bin/php-cli"```.

**Comment by trishaoconnor** [comment]
Thank you @pfabri and @dicksonlaw583  for your help. I changed the plugin folder's name as you suggested and the install button appeared. I also got an error report when I clicked install. I turned on the error reports and this is what I got back.

exception 'Omeka_Validate_Exception' with message 'Name: Name of element set must be unique.' in /home/trishaoc/public_html/ccccms41/application/libraries/Omeka/Record/AbstractRecord.php:535
Stack trace:
#0 /home/trishaoc/public_html/ccccms41/application/libraries/Omeka/Record/Builder/AbstractBuilder.php(67): Omeka_Record_AbstractRecord->save()
#1 /home/trishaoc/public_html/ccccms41/application/libraries/globals.php(740): Omeka_Record_Builder_AbstractBuilder->build()
#2 /home/trishaoc/public_html/ccccms41/plugins/IiifItems/libraries/IiifItems/Integration/Files.php(26): insert_element_set(Array, Array)
#3 /home/trishaoc/public_html/ccccms41/plugins/IiifItems/IiifItemsPlugin.php(42): IiifItems_Integration_Files->install()
#4 [internal function]: IiifItemsPlugin->hookInstall(Array)
#5 /home/trishaoc/public_html/ccccms41/application/libraries/Omeka/Plugin/Broker.php(145): call_user_func(Array, Array)
#6 /home/trishaoc/public_html/ccccms41/application/libraries/Omeka/Plugin/Installer.php(130): Omeka_Plugin_Broker->callHook('install', Array, Object(Plugin))
#7 /home/trishaoc/public_html/ccccms41/application/controllers/PluginsController.php(97): Omeka_Plugin_Installer->install(Object(Plugin))
#8 /home/trishaoc/public_html/ccccms41/application/libraries/Zend/Controller/Action.php(516): PluginsController->installAction()
#9 /home/trishaoc/public_html/ccccms41/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('installAction')
#10 /home/trishaoc/public_html/ccccms41/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /home/trishaoc/public_html/ccccms41/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#12 /home/trishaoc/public_html/ccccms41/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#13 /home/trishaoc/public_html/ccccms41/application/libraries/Omeka/Application.php(77): Zend_Application->run()
#14 /home/trishaoc/public_html/ccccms41/admin/index.php(28): Omeka_Application->run()
#15 {main}

Any ideas on what I must do from here? I've already tried deleting the contents of the folder and reinstalling them from Trash. 

Kind regards, 

Trisha

**Comment by dicksonlaw583** [comment]
@trishaoconnor:

Please go to Settings - Element Sets to delete the IIIF-related element sets, then retry.

If you downloaded the plugin from Omeka.org and the problem persists, please retry with this link from GitHub (which has a recent addition avoiding the message you described): 
 
https://codeload.github.com/utlib/IiifItems/zip/master

With the GitHub link, please remember to rename it back to ```IiifItems``` before uploading.

**Comment by trishaoconnor** [comment]
@dicksonlaw583 
When I deleted the Element sets and tried installing again I another error response about the item type. So I will tried the GitHub link to see if that will install without issue. I've received the following error report: 
RuntimeException
The configured PHP path (/usr/bin/php) does not point to a PHP-CLI binary.

exception 'RuntimeException' with message 'The configured PHP path (/usr/bin/php) does not point to a PHP-CLI binary.' in /home/trishaoc/public_html/ccccms41/application/libraries/Omeka/Job/Process/Dispatcher.php:124
Stack trace:
#0 /home/trishaoc/public_html/ccccms41/application/libraries/Omeka/Job/Process/Dispatcher.php(93): Omeka_Job_Process_Dispatcher::_checkCliPath('/usr/bin/php')
#1 /home/trishaoc/public_html/ccccms41/application/libraries/Omeka/Job/Process/Dispatcher.php(28): Omeka_Job_Process_Dispatcher::getPHPCliPath()
#2 /home/trishaoc/public_html/ccccms41/application/libraries/Omeka/Job/Dispatcher/Adapter/BackgroundProcess.php(31): Omeka_Job_Process_Dispatcher::startProcess('Omeka_Job_Proce...', Object(User), Array)
#3 /home/trishaoc/public_html/ccccms41/application/libraries/Omeka/Job/Dispatcher/Default.php(150): Omeka_Job_Dispatcher_Adapter_BackgroundProcess->send('{"className":"I...', Array)
#4 /home/trishaoc/public_html/ccccms41/plugins/IiifItems/libraries/IiifItems/Migration/0_0_1_6.php(38): Omeka_Job_Dispatcher_Default->sendLongRunning('IiifItems_Job_A...', Array)
#5 /home/trishaoc/public_html/ccccms41/plugins/IiifItems/libraries/IiifItems/Integration/System.php(75): IiifItems_Migration_0_0_1_6->up()
#6 /home/trishaoc/public_html/ccccms41/plugins/IiifItems/libraries/IiifItems/Integration/System.php(21): IiifItems_Integration_System->__addUuids()
#7 /home/trishaoc/public_html/ccccms41/plugins/IiifItems/IiifItemsPlugin.php(42): IiifItems_Integration_System->install()
#8 [internal function]: IiifItemsPlugin->hookInstall(Array)
#9 /home/trishaoc/public_html/ccccms41/application/libraries/Omeka/Plugin/Broker.php(145): call_user_func(Array, Array)
#10 /home/trishaoc/public_html/ccccms41/application/libraries/Omeka/Plugin/Installer.php(130): Omeka_Plugin_Broker->callHook('install', Array, Object(Plugin))
#11 /home/trishaoc/public_html/ccccms41/application/controllers/PluginsController.php(97): Omeka_Plugin_Installer->install(Object(Plugin))
#12 /home/trishaoc/public_html/ccccms41/application/libraries/Zend/Controller/Action.php(516): PluginsController->installAction()
#13 /home/trishaoc/public_html/ccccms41/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('installAction')
#14 /home/trishaoc/public_html/ccccms41/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#15 /home/trishaoc/public_html/ccccms41/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#16 /home/trishaoc/public_html/ccccms41/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#17 /home/trishaoc/public_html/ccccms41/application/libraries/Omeka/Application.php(77): Zend_Application->run()
#18 /home/trishaoc/public_html/ccccms41/admin/index.php(28): Omeka_Application->run()
#19 {main}

**Comment by dicksonlaw583** [comment]
@trishaoconnor:

That error is the same one as pfabri's earlier on, which is caused by a mis-configured long-running job dispatcher on your installation.

Please set the ```background.php.path``` entry in your Omeka instance's ```application/config/config.ini``` file to another PHP-CLI binary, or ask on forum.omeka.org for help on setting up your environment.

**Comment by trishaoconnor** [comment]
Thanks, @dicksonlaw583.
